name: skripsi_wap
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter_local_notifications: ^12.0.1+1
  firebase_core: ^1.24.0
  firebase_messaging: ^13.1.0
  get_cli: ^1.8.1
  http: ^0.13.5
  shared_preferences: ^2.0.15
  get: 4.6.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

