name: skripsi_wap
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  auto_route: ^5.0.4
  cached_network_image: ^3.2.3
  connectivity_plus: ^3.0.2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  dio_logger: ^4.0.8+8
  envied: ^0.3.0
  equatable: ^2.0.5
  firebase_core: ^2.4.0
  firebase_installations: ^16.3.6
  firebase_messaging: ^14.2.0
  flutter:
    sdk: flutter
  flutter_exif_rotation: ^0.5.1
  flutter_image_compress: ^1.1.3
  flutter_local_notifications: ^13.0.0
  flutter_screenutil: ^5.6.0
  flutter_secure_storage: ^7.0.1
  flutter_staggered_grid_view: ^0.6.2
  flutter_svg: ^1.1.6
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  hive_flutter: ^1.1.0
  http: ^0.13.5
  image_picker: ^0.8.6
  intl: ^0.18.0
  logger: ^1.1.0
  path_provider: ^2.0.11
  provider: ^6.0.5
  url_launcher: ^6.1.7

dev_dependencies:
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3
  envied_generator: ^0.3.0
  flutter_gen_runner: ^5.1.0+1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  hive_generator: ^2.0.0
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true

  assets:
    - assets/navigation/
    - assets/outline/
    - assets/solid/
    - assets/image/

flutter_gen:
  output: lib/config/ # Optional (default: lib/gen/)
  line_length: 120 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true

  assets:
    outputs:
      class_name: WAssets

  colors:
    outputs:
      class_name: WColors
    inputs:
      - assets/color/color.xml
